# vscode-kubernetes-tools: exclude
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test-cluster
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "enable-admission-plugins": "NamespaceLifecycle,LimitRanger,ServiceAccount,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,PersistentVolumeClaimResize,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"
# WHEN CHANGING REMEMBER TO APPLY LABELS TO NAMESPACE
# kubectl label namespace default MAC=enabled
nodes:
- role: control-plane
  image: kindest/node:v1.27.3
  extraMounts:
  - hostPath: /proc
    containerPath: /proc-host
  - hostPath: /usr/src
    containerPath: /usr/src
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
- role: worker
  image: kindest/node:v1.27.3
- role: worker
  image: kindest/node:v1.27.3

  


