apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-pod
spec:
  containers:
  - name: cpu-stress-container
    image: ubuntu:latest
    command: ["stress-ng"]
    args: ["--cpu", "1", "--timeout", "3600s", "--metrics-brief"]
