apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    name: testpod
  namespace: default
spec:
  containers:
  - name: test
    image: centos:7
    command:
      - /bin/bash
    args:
      - -c
      - trap "exit" TERM; while :; do sleep 1; done
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
    