# A webhook configuration to forward all pod creation requests to the controller

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-admission-controller
  labels:
    app: mutating-admission-controller
webhooks:
  - name: mutating-admission-controller.default.svc.cluster.local
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSm1wWUpzSnBvMU13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBME1EUXdPRFUxTkRGYUZ3MHpOREEwTURJd09UQXdOREZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURCb0FpcitJWUVmcTdGMEJmcWgxaFBSZVpjc1RGeXk0ampBZzliVDd4OWRSVnE4bGN5T25Pb01Nb0gKSGtKdHU1c09iVWw4MVp6TUZSZ0lscVIvVDNlaDFzRXFQVnJncmJ6SlAvaGZqcGFGSFpaTFdtQmZHRVU4Tld6MwpySGtpUXJtVnNzV1NsN3NzR2ZTQy9FZmN1MmZaNGV2N3VwMEo5ZlJmcDZpcXR4TUZYMDRCQ0JSYkU5SXJHZkZqCmdiNVJ6SjFSZ1BrREdGazBoVmd6N1RqZEJlRDdCeW54QUUzN3lRWnBML0RpSEdlaWxtQVBEYkhRSzVLSlF3b3AKUVNEMGQ5M3lDRHovaTF5Ukh5NlhBNlpRdkdmRjdUTXlhcUpEYTBrRTNtTDJ3M2J2cXVmK2FXZ3Y0RjVmQXJBagpFbEErS0k2RUhMR2Q2dms3OVVCcjNLSlREK2pQQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSMyt1VVk2cVlXS1V0SU83ZExOdytnaFo0ZTVEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQStmT0FsWWdjbAovVDBVbjdpZG9FY2Q3TUk0bWpYd0N2eUt6MjNQbzNQTHdwY0JKVUNtVGNQRDNRWDNVclR1QU1kRzFjU1AxSUxRCkJpaHlDeFFtOW95anRIRHladDg1SVU5WGg4YnlUNzh3N2JOc0ZvZDAzakMzVHE5SnV3WjlpYVhncnMrbUdEdmIKbTdBT2laWSs5MnNsZ3lvNklNMzNFVG1UeWhTS3FOcktvaTJSZSs1Tlh2MXBJd3NHTFluWno3dXlIR1BVanA3awo0MCtmdXMwdGxvWmloSjQrRzNnL05Eb2JvWnhySTV2QjNFL0FBMU4xM25GVldtMXlta1V3aFhyODdJeExrd1R5Ck9VMGd0WURFR1VkYXI4eWdhRVJ6NnBsYk9BVTlraUwzTk1jUm1VUUxFcTIrTi9GTkhWRTlGMGt3emtrajhvaHUKNEJUL1czb2lkcWxzCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K 
      service:
        name: mutating-admission-controller
        namespace: default
        path: "/mutate"
        port: 443
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
    admissionReviewVersions: ["v1"]
    timeoutSeconds: 5
    reinvocationPolicy: Never
    failurePolicy: Fail  # Fail for better debugging - do we want ignore in prod?
    namespaceSelector:
      matchLabels:
        MAC: enabled
