{
 "title": "Kepler Exporter Dashboard",
 "description": "Dashboard for Kepler Exporter",
 "time": { "from": "now-1m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kepler_container_package_joules_total, container_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}, pod_name)"
    }
   },
   { "name": "coal", "label": "Coal Coeff", "query": "2.23" },
   { "name": "natural_gas", "label": "Natural Gas Coeff", "query": "0.91" },
   { "name": "petroleum", "label": "Petroleum Coeff", "query": "2.13" },
   { "name": "watt_per_second_to_kWh", "query": "0.000000277777777777778" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Power Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Power Consumption (W)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (instance) (irate(kepler_container_package_joules_total{container_namespace=~\"default\", pod_name=~\"$pod\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{pod_name}} / {{instance}} / PKG"
    },
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_gpu_joules_total{container_namespace=~\"default\", pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / GPU"
    }
   ]
  },
  {
   "title": "Pod Power Consumption (W) on node: kind-worker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (pod_name, instance) (irate(kepler_container_package_joules_total{container_namespace=~\"default\", pod_name=~\"$pod\", instance=~\"kind-worker\"}[1m]))",
     "legendFormat": "{{pod_name}} / {{instance}} / PKG"
    },
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_gpu_joules_total{container_namespace=~\"default\", pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / GPU"
    }
   ]
  },
  {
   "title": "Pod Power Consumption (W) on Node: kind-worker2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "(irate(kepler_container_package_joules_total{container_namespace=~\"default\", pod_name=~\"$pod\", instance=~\"kind-worker2\"}[1m]))",
     "legendFormat": "{{pod_name}} / {{instance}} / PKG"
    },
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_gpu_joules_total{container_namespace=~\"default\", pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / GPU"
    }
   ]
  },
  {
   "title": "Total Power Consumption (W) by Node ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by (instance) (irate(kepler_container_package_joules_total{container_namespace=~\"$namespace\", instance=~\"$instance\"}[1h:1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Power Consumption (kWh per day) in Namespace: $namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 39 },
   "targets": [
    {
     "expr": "sum (\n  increase(\n   (kepler_container_package_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[24h:1m])\n  )\n) * $watt_per_second_to_kWh",
     "legendFormat": "PKG (CORE+UNCORE)"
    },
    {
     "expr": "sum (\n  increase(\n   (kepler_container_dram_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[24h:1m])\n  )\n) * $watt_per_second_to_kWh",
     "legendFormat": "DRAM"
    },
    {
     "expr": "sum (\n  increase(\n   (kepler_container_other_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[24h:1m])\n  )\n) * $watt_per_second_to_kWh",
     "legendFormat": "OTHER"
    },
    {
     "expr": "sum (\n  increase(\n   (kepler_container_gpu_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[24h:1m])\n  )\n) * $watt_per_second_to_kWh",
     "legendFormat": " GPU"
    }
   ]
  },
  {
   "title": "Total Power Consumption (PKG+DRAM+OTHER+GPU) by Namespace (kWh per day)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container_namespace) (\n  increase(\n      (kepler_container_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[24h:1m])\n  )\n) * $watt_per_second_to_kWh ",
     "legendFormat": "{{container_namespace}}"
    }
   ]
  }
 ]
}